- name: Configurar servidor NovaDeploy
  hosts: all
  become: yes
  tasks:
    - name: Instalar Node.js
      apt:
        name: nodejs
        state: present
    - name: Clonar repositório
      git:
        repo: 'https://github.com/seu-usuario/demo-devops-ci-cd.git'
        dest: /var/www/novadeploy
