name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t novadeploy -f src/docker/Dockerfile .

      - name: Simular deploy
        run: echo "Deploy realizado com sucesso!"
