name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t novadeploy -f src/docker/Dockerfile .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag da imagem
        run: docker tag novadeploy ${{ secrets.DOCKER_USERNAME }}/novadeploy:latest

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/novadeploy:latest

      - name: Finalizar deploy
        run: echo "Imagem enviada para o Docker Hub com sucesso!"
